Repository cryspen/libcrux, pull requests merged in 2025-05, with the labels that each got.

#865 Add spec and proofs for MLDSA portable sample functions
  libcrux-ml-dsa/cg/code_gen.txt
  libcrux-ml-dsa/cg/header.txt
  libcrux-ml-dsa/cg/libcrux_core.h
  libcrux-ml-dsa/cg/libcrux_mldsa65_avx2.h
  libcrux-ml-dsa/cg/libcrux_mldsa65_portable.h
  libcrux-ml-dsa/cg/libcrux_sha3_avx2.h
  libcrux-ml-dsa/cg/libcrux_sha3_portable.h
  libcrux-ml-dsa/proofs/fstar/extraction/Libcrux_ml_dsa.Specs.Simd.Portable.Sample.fst
  libcrux-ml-dsa/proofs/fstar/extraction/Libcrux_ml_dsa.Specs.fst
  libcrux-ml-dsa/proofs/fstar/extraction/Makefile
  libcrux-ml-dsa/proofs/fstar/spec/Spec.MLDSA.Math.fst
  libcrux-ml-dsa/src/lib.rs
  libcrux-ml-dsa/src/simd/portable/sample.rs
  libcrux-ml-dsa/src/specs.rs
Labels: waiting-on-review

#796 [ML-DSA] Add spec and proofs for arithmetic portable functions
  libcrux-ml-dsa/cg/code_gen.txt
  libcrux-ml-dsa/cg/header.txt
  libcrux-ml-dsa/cg/libcrux_core.h
  libcrux-ml-dsa/cg/libcrux_mldsa65_avx2.h
  libcrux-ml-dsa/cg/libcrux_mldsa65_portable.h
  libcrux-ml-dsa/cg/libcrux_sha3_avx2.h
  libcrux-ml-dsa/cg/libcrux_sha3_portable.h
  libcrux-ml-dsa/proofs/fstar/extraction/Libcrux_ml_dsa.Simd.Avx2.Arithmetic.Expanded.fst
  libcrux-ml-dsa/proofs/fstar/extraction/Libcrux_ml_dsa.Specs.Simd.Portable.Sample.fst
  libcrux-ml-dsa/proofs/fstar/extraction/Libcrux_ml_dsa.Specs.fst
  libcrux-ml-dsa/proofs/fstar/extraction/dep.graph
  libcrux-ml-dsa/proofs/fstar/spec/Spec.MLDSA.Math.fst
  libcrux-ml-dsa/src/simd/portable/arithmetic.rs
  libcrux-ml-kem/proofs/fstar/spec/Spec.Utils.fst
  libcrux-ml-kem/proofs/fstar/spec/Spec.Utils.fsti
Labels: waiting-on-author

#888 Type-based secret independence
  Cargo.toml
  libcrux-ml-kem/Cargo.toml
  libcrux-ml-kem/c.sh
  libcrux-ml-kem/c.yaml
  libcrux-ml-kem/c/code_gen.txt
  libcrux-ml-kem/c/eurydice_glue.h
  libcrux-ml-kem/c/internal/libcrux_core.h
  libcrux-ml-kem/c/internal/libcrux_mlkem_avx2.h
  libcrux-ml-kem/c/internal/libcrux_mlkem_portable.h
  libcrux-ml-kem/c/internal/libcrux_sha3_avx2.h
  libcrux-ml-kem/c/internal/libcrux_sha3_internal.h
  libcrux-ml-kem/c/libcrux_core.c
  libcrux-ml-kem/c/libcrux_core.h
  libcrux-ml-kem/c/libcrux_mlkem1024.h
  libcrux-ml-kem/c/libcrux_mlkem1024_avx2.c
  libcrux-ml-kem/c/libcrux_mlkem1024_avx2.h
  libcrux-ml-kem/c/libcrux_mlkem1024_portable.c
  libcrux-ml-kem/c/libcrux_mlkem1024_portable.h
  libcrux-ml-kem/c/libcrux_mlkem512.h
  libcrux-ml-kem/c/libcrux_mlkem512_avx2.c
  libcrux-ml-kem/c/libcrux_mlkem512_avx2.h
  libcrux-ml-kem/c/libcrux_mlkem512_portable.c
  libcrux-ml-kem/c/libcrux_mlkem512_portable.h
  libcrux-ml-kem/c/libcrux_mlkem768.h
  libcrux-ml-kem/c/libcrux_mlkem768_avx2.c
  libcrux-ml-kem/c/libcrux_mlkem768_avx2.h
  libcrux-ml-kem/c/libcrux_mlkem768_portable.c
  libcrux-ml-kem/c/libcrux_mlkem768_portable.h
  libcrux-ml-kem/c/libcrux_mlkem_avx2.c
  libcrux-ml-kem/c/libcrux_mlkem_avx2.h
  libcrux-ml-kem/c/libcrux_mlkem_portable.c
  libcrux-ml-kem/c/libcrux_mlkem_portable.h
  libcrux-ml-kem/c/libcrux_sha3.h
  libcrux-ml-kem/c/libcrux_sha3_avx2.c
  libcrux-ml-kem/c/libcrux_sha3_avx2.h
  libcrux-ml-kem/c/libcrux_sha3_internal.h
  libcrux-ml-kem/cg.yaml
  libcrux-ml-kem/cg/code_gen.txt
  libcrux-ml-kem/cg/header.txt
  libcrux-ml-kem/cg/libcrux_ct_ops.h
  libcrux-ml-kem/cg/libcrux_mlkem768_avx2.h
  libcrux-ml-kem/cg/libcrux_mlkem768_portable.h
  libcrux-ml-kem/cg/libcrux_mlkem_core.h
  libcrux-ml-kem/cg/libcrux_sha3_avx2.h
  libcrux-ml-kem/cg/libcrux_sha3_portable.h
  libcrux-ml-kem/hax.py
  libcrux-ml-kem/src/polynomial.rs
  libcrux-ml-kem/src/vector/portable.rs
  libcrux-ml-kem/src/vector/portable/arithmetic.rs
  libcrux-ml-kem/src/vector/portable/compress.rs
  libcrux-ml-kem/src/vector/portable/ntt.rs
  libcrux-ml-kem/src/vector/portable/serialize.rs
  libcrux-ml-kem/src/vector/portable/vector_type.rs
  secrets/Cargo.toml
  secrets/src/int.rs
  secrets/src/int/classify.rs
  secrets/src/int/public_integers.rs
  secrets/src/int/secret_integers.rs
  secrets/src/lib.rs
  secrets/src/traits.rs
Labels: waiting-on-author

#980 [CI] Push ML-KEM and ML-DSA benchmark results to `gh-pages` branch in this repository
  .github/workflows/mldsa-bench.yml
  .github/workflows/mlkem-bench.yml
Labels: ci

#882 Some optimizations for SHA-3 on Aarch64
  libcrux-intrinsics/src/arm64.rs
  libcrux-intrinsics/src/arm64_extract.rs
  libcrux-ml-dsa/cg/code_gen.txt
  libcrux-ml-dsa/cg/eurydice_glue.h
  libcrux-ml-dsa/cg/header.txt
  libcrux-ml-dsa/cg/libcrux_core.h
  libcrux-ml-dsa/cg/libcrux_mldsa65_avx2.h
  libcrux-ml-dsa/cg/libcrux_mldsa65_portable.h
  libcrux-ml-dsa/cg/libcrux_sha3_avx2.h
  libcrux-ml-dsa/cg/libcrux_sha3_portable.h
  libcrux-ml-kem/c/code_gen.txt
  libcrux-ml-kem/c/eurydice_glue.h
  libcrux-ml-kem/c/internal/libcrux_core.h
  libcrux-ml-kem/c/internal/libcrux_mlkem_avx2.h
  libcrux-ml-kem/c/internal/libcrux_mlkem_portable.h
  libcrux-ml-kem/c/internal/libcrux_sha3_avx2.h
  libcrux-ml-kem/c/internal/libcrux_sha3_internal.h
  libcrux-ml-kem/c/libcrux_core.c
  libcrux-ml-kem/c/libcrux_core.h
  libcrux-ml-kem/c/libcrux_mlkem1024.h
  libcrux-ml-kem/c/libcrux_mlkem1024_avx2.c
  libcrux-ml-kem/c/libcrux_mlkem1024_avx2.h
  libcrux-ml-kem/c/libcrux_mlkem1024_portable.c
  libcrux-ml-kem/c/libcrux_mlkem1024_portable.h
  libcrux-ml-kem/c/libcrux_mlkem512.h
  libcrux-ml-kem/c/libcrux_mlkem512_avx2.c
  libcrux-ml-kem/c/libcrux_mlkem512_avx2.h
  libcrux-ml-kem/c/libcrux_mlkem512_portable.c
  libcrux-ml-kem/c/libcrux_mlkem512_portable.h
  libcrux-ml-kem/c/libcrux_mlkem768.h
  libcrux-ml-kem/c/libcrux_mlkem768_avx2.c
  libcrux-ml-kem/c/libcrux_mlkem768_avx2.h
  libcrux-ml-kem/c/libcrux_mlkem768_portable.c
  libcrux-ml-kem/c/libcrux_mlkem768_portable.h
  libcrux-ml-kem/c/libcrux_mlkem_avx2.c
  libcrux-ml-kem/c/libcrux_mlkem_avx2.h
  libcrux-ml-kem/c/libcrux_mlkem_portable.c
  libcrux-ml-kem/c/libcrux_mlkem_portable.h
  libcrux-ml-kem/c/libcrux_sha3.h
  libcrux-ml-kem/c/libcrux_sha3_avx2.c
  libcrux-ml-kem/c/libcrux_sha3_avx2.h
  libcrux-ml-kem/c/libcrux_sha3_internal.h
  libcrux-ml-kem/cg/code_gen.txt
  libcrux-ml-kem/cg/eurydice_glue.h
  libcrux-ml-kem/cg/header.txt
  libcrux-ml-kem/cg/libcrux_ct_ops.h
  libcrux-ml-kem/cg/libcrux_mlkem768_avx2.h
  libcrux-ml-kem/cg/libcrux_mlkem768_portable.h
  libcrux-ml-kem/cg/libcrux_mlkem_core.h
  libcrux-ml-kem/cg/libcrux_sha3_avx2.h
  libcrux-ml-kem/cg/libcrux_sha3_portable.h
  libcrux-sha3/benches/sha3.rs
  libcrux-sha3/src/generic_keccak.rs
  libcrux-sha3/src/portable_keccak.rs
  libcrux-sha3/src/simd/arm64.rs
  libcrux-sha3/src/simd/avx2.rs
  libcrux-sha3/src/traits.rs
Labels: waiting-on-review
